language: objective-c
matrix:
  include:
    - osx_image: xcode9.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
script:
  - xcodebuild clean build -scheme OpenTerminal -sdk macosx -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
notifications:
  email: false

