language: objective-c
matrix:
  include:
    - osx_image: xcode9.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
script:
  - xcodebuild -scheme OpenTerminal -sdk macosx -configuration Release
notifications:
  email: false

